# Generated by Django 5.0.7 on 2024-08-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_themes_posts_imagesposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesposts',
            name='content',
            field=models.ImageField(upload_to='posts/%Y/%m/%d/'),
        ),
    ]
