# Generated by Django 5.0.7 on 2024-08-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_imagesposts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_banner',
            field=models.ImageField(default='hello', upload_to='posts/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='short_description',
            field=models.CharField(default='image.png', max_length=400),
            preserve_default=False,
        ),
    ]
