# Generated by Django 5.0.7 on 2024-08-07 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesposts',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.posts'),
        ),
    ]
