# Generated by Django 5.0.7 on 2024-08-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_imagesposts_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainThemes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
