# Generated by Django 5.0.7 on 2024-08-08 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_mainthemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='main_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.mainthemes'),
        ),
    ]
