# Generated by Django 5.0.7 on 2024-08-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_posts_main_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='reads',
            field=models.IntegerField(default=0),
        ),
    ]
