# Generated by Django 5.0.7 on 2024-08-10 03:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_posts_reads'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='descrip_ck',
            field=ckeditor.fields.RichTextField(default='hola'),
            preserve_default=False,
        ),
    ]
