# Generated by Django 5.0.7 on 2024-08-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_posts_descrip_ck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='description',
        ),
    ]
