# Generated by Django 5.0.7 on 2024-08-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_posts_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='descrip_ck',
            new_name='descripcion',
        ),
    ]
