# Generated by Django 5.0.7 on 2024-08-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_descrip_ck_posts_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesPosts',
        ),
    ]
