# Generated by Django 5.0.7 on 2024-08-12 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_imagesposts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Themes',
            new_name='Tags',
        ),
    ]
