# Generated by Django 5.0.7 on 2024-08-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_themes_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='theme',
            new_name='tags_post',
        ),
    ]
