# Generated by Django 5.0.7 on 2024-08-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_theme_posts_tags_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
