# Generated by Django 5.0.7 on 2024-08-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_posts_tags_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
