# Generated by Django 5.0.7 on 2024-08-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_banner',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
