# Generated by Django 5.0.7 on 2024-10-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_posts_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
